<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="Inverter_LCEE.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW pn CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Description" Caption="Description" Index="1" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="2" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="3" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="5" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="pn" Caption="pn" Index="71" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="94" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Description="Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, GRM21BR61C106KE1, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, GRM21BR61C106KE1, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, GRM21BR61C106KE1, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, Capacitor nao polarizado, CC0805KRX7R8BB10, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, Capacitor, C1608X5R1H105K08, C0805C106K8PACTU, CC0805KRX7R8BB10, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor- Not Used, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, Resistor, CRCW040221K5FKED, CRCW040210K0FKED, CRM0805-FW-R050E, CRCW0402174KFKED" Designator="C1, C1_Phase_B1, C1_Phase_B2, C1_Phase_B3, C1_Phase_B4, C1_Phase_T5, C1_Phase_T6, C1_Phase_T7, C1_Phase_T8, C2, C2_Phase_B1, C2_Phase_B2, C2_Phase_B3, C2_Phase_B4, C2_Phase_T5, C2_Phase_T6, C2_Phase_T7, C2_Phase_T8, C3_DT1, C3_DT2, C3_DT3, C3_DT4, C3_Phase_B1, C3_Phase_B2, C3_Phase_B3, C3_Phase_B4, C3_Phase_T5, C3_Phase_T6, C3_Phase_T7, C3_Phase_T8, C4_DT1, C4_DT2, C4_DT3, C4_DT4, C4_Phase_B1, C4_Phase_B2, C4_Phase_B3, C4_Phase_B4, C4_Phase_T5, C4_Phase_T6, C4_Phase_T7, C4_Phase_T8, C5_DT1, C5_DT2, C5_DT3, C5_DT4, C5_Phase_B1, C5_Phase_B2, C5_Phase_B3, C5_Phase_B4, C5_Phase_T5, C5_Phase_T6, C5_Phase_T7, C5_Phase_T8, C6_DT1, C6_DT2, C6_DT3, C6_DT4, C6_Phase_B1, C6_Phase_B2, C6_Phase_B3, C6_Phase_B4, C6_Phase_T5, C6_Phase_T6, C6_Phase_T7, C6_Phase_T8, C7_DT1, C7_DT2, C7_DT3, C7_DT4, C7_Phase_B1, C7_Phase_B2, C7_Phase_B3, C7_Phase_B4, C7_Phase_T5, C7_Phase_T6, C7_Phase_T7, C7_Phase_T8, C8_Phase_B1, C8_Phase_B2, C8_Phase_B3, C8_Phase_B4, C8_Phase_T5, C8_Phase_T6, C8_Phase_T7, C8_Phase_T8, C9_Phase_B1, C9_Phase_B2, C9_Phase_B3, C9_Phase_B4, C9_Phase_T5, C9_Phase_T6, C9_Phase_T7, C9_Phase_T8, C10, C10_Phase_B1, C10_Phase_B2, C10_Phase_B3, C10_Phase_B4, C10_Phase_T5, C10_Phase_T6, C10_Phase_T7, C10_Phase_T8, C11, C11_Phase_B1, C11_Phase_B2, C11_Phase_B3, C11_Phase_B4, C11_Phase_T5, C11_Phase_T6, C11_Phase_T7, C11_Phase_T8, C12, C12_Phase_B1, C12_Phase_B2, C12_Phase_B3, C12_Phase_B4, C12_Phase_T5, C12_Phase_T6, C12_Phase_T7, C12_Phase_T8, C13_Phase_B1, C13_Phase_B2, C13_Phase_B3, C13_Phase_B4, C13_Phase_T5, C13_Phase_T6, C13_Phase_T7, C13_Phase_T8, C14_Phase_B1, C14_Phase_B2, C14_Phase_B3, C14_Phase_B4, C14_Phase_T5, C14_Phase_T6, C14_Phase_T7, C14_Phase_T8, C15_Phase_B1, C15_Phase_B2, C15_Phase_B3, C15_Phase_B4, C15_Phase_T5, C15_Phase_T6, C15_Phase_T7, C15_Phase_T8, C16_Phase_B1, C16_Phase_B2, C16_Phase_B3, C16_Phase_B4, C16_Phase_T5, C16_Phase_T6, C16_Phase_T7, C16_Phase_T8, C17_Phase_B1, C17_Phase_B2, C17_Phase_B3, C17_Phase_B4, C17_Phase_T5, C17_Phase_T6, C17_Phase_T7, C17_Phase_T8, C18_Phase_B1, C18_Phase_B2, C18_Phase_B3, C18_Phase_B4, C18_Phase_T5, C18_Phase_T6, C18_Phase_T7, C18_Phase_T8, C19_Supply_Iso1, C19_Supply_Iso2, C19_Supply_Iso3, C19_Supply_Iso4, C19_Supply_Iso5, C19_Supply_Iso6, C19_Supply_Iso7, C19_Supply_Iso8, C20_Supply_Iso1, C20_Supply_Iso2, C20_Supply_Iso3, C20_Supply_Iso4, C20_Supply_Iso5, C20_Supply_Iso6, C20_Supply_Iso7, C20_Supply_Iso8, C21_Supply_Iso1, C21_Supply_Iso2, C21_Supply_Iso3, C21_Supply_Iso4, C21_Supply_Iso5, C21_Supply_Iso6, C21_Supply_Iso7, C21_Supply_Iso8, C22_Supply_Iso1, C22_Supply_Iso2, C22_Supply_Iso3, C22_Supply_Iso4, C22_Supply_Iso5, C22_Supply_Iso6, C22_Supply_Iso7, C22_Supply_Iso8, C23_Supply_Iso1, C23_Supply_Iso2, C23_Supply_Iso3, C23_Supply_Iso4, C23_Supply_Iso5, C23_Supply_Iso6, C23_Supply_Iso7, C23_Supply_Iso8, C24_Supply_Iso1, C24_Supply_Iso2, C24_Supply_Iso3, C24_Supply_Iso4, C24_Supply_Iso5, C24_Supply_Iso6, C24_Supply_Iso7, C24_Supply_Iso8, C25_Supply_Iso1, C25_Supply_Iso2, C25_Supply_Iso3, C25_Supply_Iso4, C25_Supply_Iso5, C25_Supply_Iso6, C25_Supply_Iso7, C25_Supply_Iso8, C30_GateCircuit_B1, C30_GateCircuit_B2, C30_GateCircuit_B3, C30_GateCircuit_B4, C30_GateCircuit_B5, C30_GateCircuit_B6, C30_GateCircuit_B7, C30_GateCircuit_B8, C31_GateCircuit_B1, C31_GateCircuit_B2, C31_GateCircuit_B3, C31_GateCircuit_B4, C31_GateCircuit_B5, C31_GateCircuit_B6, C31_GateCircuit_B7, C31_GateCircuit_B8, C35, C36, C37, C38, C39, C40, C42, Cbst1, Cin1_Supply_Iso1, Cin1_Supply_Iso2, Cin1_Supply_Iso3, Cin1_Supply_Iso4, Cin1_Supply_Iso5, Cin1_Supply_Iso6, Cin1_Supply_Iso7, Cin1_Supply_Iso8, Cin2_Supply_Iso1, Cin2_Supply_Iso2, Cin2_Supply_Iso3, Cin2_Supply_Iso4, Cin2_Supply_Iso5, Cin2_Supply_Iso6, Cin2_Supply_Iso7, Cin2_Supply_Iso8, Cinx1, Cout1, Css1, R1, R1_Phase_B1, R1_Phase_B2, R1_Phase_B3, R1_Phase_B4, R1_Phase_T5, R1_Phase_T6, R1_Phase_T7, R1_Phase_T8, R2, R2_Phase_B1, R2_Phase_B2, R2_Phase_B3, R2_Phase_B4, R2_Phase_T5, R2_Phase_T6, R2_Phase_T7, R2_Phase_T8, R3, R3_Phase_B1, R3_Phase_B2, R3_Phase_B3, R3_Phase_B4, R3_Phase_T5, R3_Phase_T6, R3_Phase_T7, R3_Phase_T8, R4, R4_Phase_B1, R4_Phase_B2, R4_Phase_B3, R4_Phase_B4, R4_Phase_T5, R4_Phase_T6, R4_Phase_T7, R4_Phase_T8, R5, R5_Phase_B1, R5_Phase_B2, R5_Phase_B3, R5_Phase_B4, R5_Phase_T5, R5_Phase_T6, R5_Phase_T7, R5_Phase_T8, R6_DT1, R6_DT2, R6_DT3, R6_DT4, R6_Phase_B1, R6_Phase_B2, R6_Phase_B3, R6_Phase_B4, R6_Phase_T5, R6_Phase_T6, R6_Phase_T7, R6_Phase_T8, R7_DT1, R7_DT2, R7_DT3, R7_DT4, R7_Phase_B1, R7_Phase_B2, R7_Phase_B3, R7_Phase_B4, R7_Phase_T5, R7_Phase_T6, R7_Phase_T7, R7_Phase_T8, R8_DT1, R8_DT2, R8_DT3, R8_DT4, R8_Phase_B1, R8_Phase_B2, R8_Phase_B3, R8_Phase_B4, R8_Phase_T5, R8_Phase_T6, R8_Phase_T7, R8_Phase_T8, R9_DT1, R9_DT2, R9_DT3, R9_DT4, R9_Phase_B1, R9_Phase_B2, R9_Phase_B3, R9_Phase_B4, R9_Phase_T5, R9_Phase_T6, R9_Phase_T7, R9_Phase_T8, R10_DT1, R10_DT2, R10_DT3, R10_DT4, R10_Phase_B1, R10_Phase_B2, R10_Phase_B3, R10_Phase_B4, R10_Phase_T5, R10_Phase_T6, R10_Phase_T7, R10_Phase_T8, R11_DT1, R11_DT2, R11_DT3, R11_DT4, R11_Phase_B1, R11_Phase_B2, R11_Phase_B3, R11_Phase_B4, R11_Phase_T5, R11_Phase_T6, R11_Phase_T7, R11_Phase_T8, R12, R12_Phase_B1, R12_Phase_B2, R12_Phase_B3, R12_Phase_B4, R12_Phase_T5, R12_Phase_T6, R12_Phase_T7, R12_Phase_T8, R13_DT1, R13_DT2, R13_DT3, R13_DT4, R13_Phase_B1, R13_Phase_B2, R13_Phase_B3, R13_Phase_B4, R13_Phase_T5, R13_Phase_T6, R13_Phase_T7, R13_Phase_T8, R14_DT1, R14_DT2, R14_DT3, R14_DT4, R14_Phase_B1, R14_Phase_B2, R14_Phase_B3, R14_Phase_B4, R14_Phase_T5, R14_Phase_T6, R14_Phase_T7, R14_Phase_T8, R15_DT1, R15_DT2, R15_DT3, R15_DT4, R15_Phase_B1, R15_Phase_B2, R15_Phase_B3, R15_Phase_B4, R15_Phase_T5, R15_Phase_T6, R15_Phase_T7, R15_Phase_T8, R16_DT1, R16_DT2, R16_DT3, R16_DT4, R16_Phase_B1, R16_Phase_B2, R16_Phase_B3, R16_Phase_B4, R16_Phase_T5, R16_Phase_T6, R16_Phase_T7, R16_Phase_T8, R17_DT1, R17_DT2, R17_DT3, R17_DT4, R17_Phase_B1, R17_Phase_B2, R17_Phase_B3, R17_Phase_B4, R17_Phase_T5, R17_Phase_T6, R17_Phase_T7, R17_Phase_T8, R18, R18_Phase_B1, R18_Phase_B2, R18_Phase_B3, R18_Phase_B4, R18_Phase_T5, R18_Phase_T6, R18_Phase_T7, R18_Phase_T8, R19, R19_Phase_B1, R19_Phase_B2, R19_Phase_B3, R19_Phase_B4, R19_Phase_T5, R19_Phase_T6, R19_Phase_T7, R19_Phase_T8, R20, R20_Phase_B1, R20_Phase_B2, R20_Phase_B3, R20_Phase_B4, R20_Phase_T5, R20_Phase_T6, R20_Phase_T7, R20_Phase_T8, R21, R21_Phase_B1, R21_Phase_B2, R21_Phase_B3, R21_Phase_B4, R21_Phase_T5, R21_Phase_T6, R21_Phase_T7, R21_Phase_T8, R22, R22_Phase_B1, R22_Phase_B2, R22_Phase_B3, R22_Phase_B4, R22_Phase_T5, R22_Phase_T6, R22_Phase_T7, R22_Phase_T8, R23, R23_Phase_B1, R23_Phase_B2, R23_Phase_B3, R23_Phase_B4, R23_Phase_T5, R23_Phase_T6, R23_Phase_T7, R23_Phase_T8, R24, R24_Phase_B1, R24_Phase_B2, R24_Phase_B3, R24_Phase_B4, R24_Phase_T5, R24_Phase_T6, R24_Phase_T7, R24_Phase_T8, R25, R25_Phase_B1, R25_Phase_B2, R25_Phase_B3, R25_Phase_B4, R25_Phase_T5, R25_Phase_T6, R25_Phase_T7, R25_Phase_T8, R26, R26_Supply_Iso1, R26_Supply_Iso2, R26_Supply_Iso3, R26_Supply_Iso4, R26_Supply_Iso5, R26_Supply_Iso6, R26_Supply_Iso7, R26_Supply_Iso8, R27_Supply_Iso1, R27_Supply_Iso2, R27_Supply_Iso3, R27_Supply_Iso4, R27_Supply_Iso5, R27_Supply_Iso6, R27_Supply_Iso7, R27_Supply_Iso8, R28_Supply_Iso1, R28_Supply_Iso2, R28_Supply_Iso3, R28_Supply_Iso4, R28_Supply_Iso5, R28_Supply_Iso6, R28_Supply_Iso7, R28_Supply_Iso8, R29_Supply_Iso1, R29_Supply_Iso2, R29_Supply_Iso3, R29_Supply_Iso4, R29_Supply_Iso5, R29_Supply_Iso6, R29_Supply_Iso7, R29_Supply_Iso8, R30_Supply_Iso1, R30_Supply_Iso2, R30_Supply_Iso3, R30_Supply_Iso4, R30_Supply_Iso5, R30_Supply_Iso6, R30_Supply_Iso7, R30_Supply_Iso8, R31_Supply_Iso1, R31_Supply_Iso2, R31_Supply_Iso3, R31_Supply_Iso4, R31_Supply_Iso5, R31_Supply_Iso6, R31_Supply_Iso7, R31_Supply_Iso8, R36, R38, R39, R39_GateCircuit_B1, R39_GateCircuit_B2, R39_GateCircuit_B3, R39_GateCircuit_B4, R39_GateCircuit_B5, R39_GateCircuit_B6, R39_GateCircuit_B7, R39_GateCircuit_B8, R40_GateCircuit_B1, R40_GateCircuit_B2, R40_GateCircuit_B3, R40_GateCircuit_B4, R40_GateCircuit_B5, R40_GateCircuit_B6, R40_GateCircuit_B7, R40_GateCircuit_B8, R41_GateCircuit_B1, R41_GateCircuit_B2, R41_GateCircuit_B3, R41_GateCircuit_B4, R41_GateCircuit_B5, R41_GateCircuit_B6, R41_GateCircuit_B7, R41_GateCircuit_B8, R43_GateCircuit_B1, R43_GateCircuit_B2, R43_GateCircuit_B3, R43_GateCircuit_B4, R43_GateCircuit_B5, R43_GateCircuit_B6, R43_GateCircuit_B7, R43_GateCircuit_B8, R44_GateCircuit_B1, R44_GateCircuit_B2, R44_GateCircuit_B3, R44_GateCircuit_B4, R44_GateCircuit_B5, R44_GateCircuit_B6, R44_GateCircuit_B7, R44_GateCircuit_B8, R45_GateCircuit_B1, R45_GateCircuit_B2, R45_GateCircuit_B3, R45_GateCircuit_B4, R45_GateCircuit_B5, R45_GateCircuit_B6, R45_GateCircuit_B7, R45_GateCircuit_B8, R48, R49, R50, R51, R52, R53, R54, R55, R56, R57, R58, R59, R60, R61, R62, R63, R64, R65, R66, R67, R68, R69, R70, R71, R72, R73, R74, R75, R76, R77, R78, R79, R80, R81, R82, R99_GateCircuit_B1, R99_GateCircuit_B2, R99_GateCircuit_B3, R99_GateCircuit_B4, R99_GateCircuit_B5, R99_GateCircuit_B6, R99_GateCircuit_B7, R99_GateCircuit_B8, Rfb1, Rfb2, Rsns1, Rt1" Footprint="0805_W" Quantity="673" pn="&#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, C0805C473K8RAC7800, C0805C473K8RAC7800, C0805C473K8RAC7800, C0805C473K8RAC7800, C0805C473K8RAC7800, C0805C473K8RAC7800, C0805C473K8RAC7800, C0805C473K8RAC7800, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, C0805C223K8RACTU, C0805C223K8RACTU, C0805C223K8RACTU, C0805C223K8RACTU, C0805C223K8RACTU, C0805C223K8RACTU, C0805C223K8RACTU, C0805C223K8RACTU, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, 08053C101KAT2A, 08053C101KAT2A, 08053C101KAT2A, 08053C101KAT2A, 08053C101KAT2A, 08053C101KAT2A, 08053C101KAT2A, 08053C101KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, &#91;NoParam&#93;, &#91;NoParam&#93;, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, 08053C104KAT2A, 08053C104KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, C0805C106K8PACTU, 08053C104KAT2A, RMCF0805JT680R, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT4K70, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT680R, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT4K70, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT47K0, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT47K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT560K, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT22K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT47K0, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT5K60, RMCF0805JT47K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT47K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT47K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT47K0, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT47K0, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT47K0, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT47K0, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT47K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1K00, &#91;NoParam&#93;, RMCF0805JT1K00, RMCF0805JT4K70, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K