<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="LogicsOnly.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW pn CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Name CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Designator" Caption="Designator" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="103"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="108"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="108"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="109"></COLUMN>
    <COLUMN Name="pn" Caption="pn" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Name" Caption="Manufacturer Name" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number" Caption="Manufacturer Part Number" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Designator="C1, C2, C3.DTA, C3.DTB, C3.DTC, C3.DTD, C4.DTA, C4.DTB, C4.DTC, C4.DTD, C5.DTA, C5.DTB, C5.DTC, C5.DTD, C6.DTA, C6.DTB, C6.DTC, C6.DTD, C7.DTA, C7.DTB, C7.DTC, C7.DTD, C10, C11, C12, C35, C36, C37, C38, C39, C40, C42, Cbst1, Cinx1, Cout1, Css1, R1, R2, R3, R4, R5, R6.DTA, R6.DTB, R6.DTC, R6.DTD, R7.DTA, R7.DTB, R7.DTC, R7.DTD, R8.DTA, R8.DTB, R8.DTC, R8.DTD, R9.DTA, R9.DTB, R9.DTC, R9.DTD, R10.DTA, R10.DTB, R10.DTC, R10.DTD, R11.DTA, R11.DTB, R11.DTC, R11.DTD, R12, R13.DTA, R13.DTB, R13.DTC, R13.DTD, R14.DTA, R14.DTB, R14.DTC, R14.DTD, R15.DTA, R15.DTB, R15.DTC, R15.DTD, R16.DTA, R16.DTB, R16.DTC, R16.DTD, R17.DTA, R17.DTB, R17.DTC, R17.DTD, R18, R19, R20, R21, R22, R23, R24, R25, R26, R36, R38, R39, R48, R49, R50, R51, R52, R53, R54, R55, R56, R57, R58, R59, R60, R61, R62, R63, R64, R65, R66, R67, R68, R69, R70, R71, R72, R73, R74, R75, R76, R77, R78, R79, R80, R81, R82, Rfb1, Rfb2, Rsns1, Rt1" Footprint="0805_W" Quantity="137" Value="not used, not used, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, 10nF, &#91;NoValue&#93;, &#91;NoValue&#93;, &#91;NoValue&#93;, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 1uF, 10uF, 100nF, 680R, 4k7, 220, 4k7, 47k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 47k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 10k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47R, 47R, 47R, 1k, 100k, 1k, 4.7k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 47k, 1k, 1k, 1k, 1k, 47k, 47k, 47k, 47k, 1k, 330R, 47R, 47R, 47R, 47R, 47R, &#91;NoParam&#93;, 47R, 47R, 47R, 21.5k, 10k, 50m, 180k" pn="&#91;NoParam&#93;, &#91;NoParam&#93;, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, C0805C104K8RACTU, 08053C104KAT2A, 08053C104KAT2A, &#91;NoParam&#93;, C0805C106K8PACTU, 08053C104KAT2A, RMCF0805JT680R, RMCF0805JT4K70, RMCF0805JT680R, RMCF0805JT4K70, RMCF0805JT47K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT47K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT1K00, &#91;NoParam&#93;, RMCF0805JT1K00, RMCF0805JT4K70, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT1K00, RMCF0805JT1K00, RMCF0805JT1K00, RMCF0805JT1K00, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT1K00, RMCF0805JT330R, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT47R0, 47R, RMCF0805JT47R0, RMCF0805JT47R0, RMCF0805JT47R0, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;" Manufacturer_Name="&#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, MuRata, MuRata, MuRata, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, TDK, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, Vishay-Dale, Vishay-Dale, Bourns, Vishay-Dale" Manufacturer_Part_Number="&#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, GRM21BR61C106KE15L, GRM21BR61C106KE15L, GRM21BR61C106KE15L, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, C1608X5R1H105K080AB, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, CRCW040221K5FKED, CRCW040210K0FKED, CRM0805-FW-R050ELF, CRCW0402174KFKED"></ROW>
    <ROW Designator="Cin3" Footprint="1210_W" Quantity="1" Value="3.3uF" pn="" Manufacturer_Name="TDK" Manufacturer_Part_Number="C3225X7S2A335K200AB"></ROW>
    <ROW Designator="D1, D3, D9, D26, D27, D28, D29, D32, D445" Footprint="LED_0805" Quantity="9" Value="Green LED, Green LED, Yellow LED, Red LED, Red LED, Red LED, Red LED, Green LED, Green LED" pn="SML-LXR85GC-TR, SML-LXR85GC-TR, SML-LXR85YC-TR, SML-LXR85IC-TR, SML-LXR85IC-TR, SML-LXR85IC-TR, SML-LXR85IC-TR, SML-LXR85GC-TR, SML-LXR85GC-TR" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="D2, D4, D5.DTA, D5.DTB, D5.DTC, D5.DTD, D6.DTA, D6.DTB, D6.DTC, D6.DTD, D7.DTA, D7.DTB, D7.DTC, D7.DTD, D8.DTA, D8.DTB, D8.DTC, D8.DTD, D21, D22, D23, D24, D25, D33" Footprint="SOD-123" Quantity="24" Value="1N4148, 1N4148, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, B240A" pn="1N4148W-TP, 1N4148W-TP, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, &#91;NoParam&#93;, BAT46ZFILM, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, B360A-13-F" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="Faults" Footprint="" Quantity="1" Value="Header 7" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="Fix1, Fix2, Fix3, Fix4" Footprint="Pino" Quantity="4" Value="Pin" pn="908-100; RM2X12MM 2701" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="INV_CONTROL, PWM_AB, PWM_CN" Footprint="RJ-45" Quantity="3" Value="RJ-45" pn="A-2004-2-4-LPS-N-R" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="JP1.DTA, JP1.DTB, JP1.DTC, JP1.DTD, JP4.DTA, JP4.DTB, JP4.DTC, JP4.DTD" Footprint="Jumper" Quantity="8" Value="solder jumper" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="JP2.DTA, JP2.DTB, JP2.DTC, JP2.DTD, JP3.DTA, JP3.DTB, JP3.DTC, JP3.DTD, JP6.DTA, JP6.DTB, JP6.DTC, JP6.DTD, JP7.DTA, JP7.DTB, JP7.DTC, JP7.DTD" Footprint="Jumper" Quantity="16" Value="solder jumper" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="JP5" Footprint="HDR1X2" Quantity="1" Value="Header 2" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="K1, K2" Footprint="Relay - SPDT" Quantity="2" Value="Relay 9V coil - 10A" pn="G5LE-14-DC9" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="L" Footprint="SRN8040T - Inductor" Quantity="1" Value="8.2uH" pn="SRN8040-8R2Y" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="Manual Reset" Footprint="Tactile SPST-NO" Quantity="1" Value="Tactile SPST-NO" pn="FSM4JH" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="P3, P4" Footprint="KK-3_G" Quantity="2" Value="Bornier" pn="1935174" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="P7" Footprint="HDR1X3" Quantity="1" Value="Header 3" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="P3000" Footprint="HDR2X5" Quantity="1" Value="Header 5X2" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="Q1, Q2" Footprint="SOT-23-TT3_L" Quantity="2" Value="BC847" pn="BC847BLT1G" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="Q7" Footprint="SOT-23-TT3_N" Quantity="1" Value="BC847" pn="BC847BLT1G" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="Signals_1, Signals_2, Signals_3, Signals_4" Footprint="HDR1X5" Quantity="4" Value="Header 5" pn="" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="SUPPLY" Footprint="3 Pin  Borner" Quantity="1" Value="Bornier" pn="1935174" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="U1" Footprint="10MSOP" Quantity="1" Value="LM25011MYX" pn="LM25011MYX/NOPB" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="U3.DTA, U3.DTB, U3.DTC, U3.DTD, U4.DTA, U4.DTB, U4.DTC, U4.DTD, U12" Footprint="SOIC-14N" Quantity="9" Value="MC74HC08AD, MC74HC08AD, MC74HC08AD, MC74HC08AD, MC74HC02ADG, MC74HC02ADG, MC74HC02ADG, MC74HC02ADG, 74LVC06AS14" pn="MC74HC08ADG, MC74HC08ADG, MC74HC08ADG, MC74HC08ADG, MC74HC02ADG, MC74HC02ADG, MC74HC02ADG, MC74HC02ADG, 74LVC06AS14-13" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="U6" Footprint="LM7805" Quantity="1" Value="LM7805" pn="MC7805BDTG" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="U10, U11, U14, U15" Footprint="SO14-Wide" Quantity="4" Value="SN74LS32, SN74HCT125, SN74HCT125, SN74HCT125" pn="SN74LS32NSR, SN74HCT125DR, &#91;NoParam&#93;, &#91;NoParam&#93;" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
    <ROW Designator="U13" Footprint="SOIC16_Wide" Quantity="1" Value="SN74LS279" pn="SN74LS279ANSR" Manufacturer_Name="" Manufacturer_Part_Number=""></ROW>
  </ROWS>
</GRID>
