<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="OnePhase.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW pn CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Designator" Caption="Designator" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="pn" Caption="pn" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Designator="C1.1, C1.2, C2.1, C2.2, C3.1, C3.2, C4.1, C4.2, C5.1, C5.2, C6.1, C6.2, C7.1, C7.2, C8.1, C8.2, C9.1, C9.2, C10.1, C10.2, C11.1, C11.2, C12.1, C12.2, C13.1, C13.2, C14.1, C14.2, C15.1, C15.2, C16.1, C16.2, C17.1, C17.2, C18.1, C18.2, C19.1, C19.2, C20.1, C20.2, C21.1, C21.2, C22.1, C22.2, C23.1, C23.2, C24.1, C24.2, C25.1, C25.2, C30.1, C30.2, C31.1, C31.2, Cin1.1, Cin1.2, Cin2.1, Cin2.2, R1.1, R1.2, R2.1, R2.2, R3.1, R3.2, R4.1, R4.2, R5.1, R5.2, R6.1, R6.2, R7.1, R7.2, R8.1, R8.2, R9.1, R9.2, R10.1, R10.2, R11.1, R11.2, R12.1, R12.2, R13.1, R13.2, R14.1, R14.2, R15.1, R15.2, R16.1, R16.2, R17.1, R17.2, R18.1, R18.2, R19.1, R19.2, R20.1, R20.2, R21.1, R21.2, R22.1, R22.2, R23.1, R23.2, R24.1, R24.2, R25.1, R25.2, R26.1, R26.2, R27.1, R27.2, R28.1, R28.2, R29.1, R29.2, R30.1, R30.2, R31.1, R31.2, R39.1, R39.2, R40.1, R40.2, R41.1, R41.2, R43.1, R43.2, R44.1, R44.2, R45.1, R45.2, R99.1, R99.2" Footprint="0805_W" Quantity="134" Value="not used, not used, not used, not used, not used, not used, not used, not used, 47pF, 47pF, not used, not used, 22nF, 22nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 2.2uF, 2.2uF, 100nF, 100nF, 100pF, 100pF, 2.2uF, 2.2uF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 2.2uF, 2.2uF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 100nF, 1nF, 1nF, 10nF, 10nF, 10nF, 10nF, 1uF, 1uF, 100nF, 100nF, 10k, 10k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 100k, 22k, 22k, 2.0k, 2.0k, 22k, 22k, 4.7k, 4.7k, 22k, 22k, 10k, 10k, 22k, 22k, 10k, 10k, 47k, 47k, not used, not used, 15k, 15k, 33k, 33k, 330R, 330R, 3.3k, 3.3k, 100R, 100R, 100R, 100R, 12K, 12K, 3.3k, 3.3k, 1R5, 1R5, 1R5, 1R5, not used, not used, 4.7k, 4.7k, 1R, 1R, 10, 10, 47k, 47k, 10R, 10R, 47k, 47k, 1R, 1R, 1R, 1R" pn="&#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, &#91;NoParam&#93;, C0805C473K8RAC7800, C0805C473K8RAC7800, &#91;NoParam&#93;, &#91;NoParam&#93;, C0805C223K8RACTU, C0805C223K8RACTU, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C225KAT2A, 08053C225KAT2A, C0805C104K8RACTU, C0805C104K8RACTU, 08053C101KAT2A, 08053C101KAT2A, 08053C225KAT2A, 08053C225KAT2A, C0805C104K8RACTU, C0805C104K8RACTU, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C225KAT2A, 08053C225KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C104KAT2A, 08053C102KAT2A, 08053C102KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C103KAT2A, 08053C105KAT2A, 08053C105KAT2A, 08053C104KAT2A, 08053C104KAT2A, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT100K, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT2K00, RMCF0805JT2K00, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT560K, RMCF0805JT560K, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT22K0, RMCF0805JT22K0, RMCF0805JT10K0, RMCF0805JT10K0, RMCF0805JT5K60, RMCF0805JT5K60, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT15K0, RMCF0805JT15K0, RMCF0805JT33K0, RMCF0805JT33K0, RMCF0805JT330R, RMCF0805JT330R, RMCF0805JT3k30, RMCF0805JT3k30, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT100R, RMCF0805JT12K0, RMCF0805JT12K0, RMCF0805JT3K30, RMCF0805JT3K30, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, RMCF0805JT1R50, &#91;NoParam&#93;, &#91;NoParam&#93;, RMCF0805JT4K70, RMCF0805JT4K70, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT10R0, RMCF0805JT10R0, RMCF0805JT47K0, RMCF0805JT47K0, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00, RMCF0805JT1R00"></ROW>
    <ROW Designator="C26, C27, C28, C29" Footprint="Capacitor Eletrolitico - duplicate" Quantity="4" Value="220uF" pn="B43305B9227M000"></ROW>
    <ROW Designator="C80, C81" Footprint="Capacitor_Pol_15x6mm" Quantity="2" Value="not used" pn=""></ROW>
    <ROW Designator="Ca1" Footprint="Capacitor_Pol_2Sizes" Quantity="1" Value="2.2uF" pn="R463R422000M1M"></ROW>
    <ROW Designator="D1.1, D1.2, D2.1, D2.2, D3.1, D3.2, D4.1, D4.2, D5.1, D5.2, D6.1, D6.2, D7.1, D7.2, D8.1, D8.2, D9.1, D9.2, D10.1, D10.2, D12.1, D12.2, D13.1, D13.2" Footprint="SOD-123" Quantity="24" Value="BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BZT52C8V2, BZT52C8V2, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z, BAT46Z" pn="BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BZT52C8V2-FDICT-ND, BZT52C8V2-FDICT-ND, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM, BAT46ZFILM"></ROW>
    <ROW Designator="DC+++, DC---, Pin_A1" Footprint="Power conector" Quantity="3" Value="screw" pn="7799"></ROW>
    <ROW Designator="GateDriver.1, GateDriver.2, U6.1, U6.2" Footprint="SOIC-8N" Quantity="4" Value="MCP14A0601, MCP14A0601, SI8421AB, SI8421AB" pn="MIC4420YM-TR;MIC4422ZM, MIC4420YM-TR;MIC4422ZM, SI8421AB-D-IS;SI8422BB-D-IS;FOD8012A, SI8421AB-D-IS;SI8422BB-D-IS;FOD8012A"></ROW>
    <ROW Designator="P1" Footprint="3 Pin  Borner" Quantity="1" Value="Bornier" pn="1935174"></ROW>
    <ROW Designator="P2, P3" Footprint="HDR1X3" Quantity="2" Value="Header 3" pn=""></ROW>
    <ROW Designator="Q1.1, Q1.2, Q2.1, Q2.2, Q3.1, Q3.2, Q4.1, Q4.2" Footprint="SOT-23-TT3_N" Quantity="8" Value="BC857, BC857, BC847, BC847, BC857B, BC857B, BC847B, BC847B" pn="BC857BLT1G, BC857BLT1G, BC847BLT1G, BC847BLT1G, BC857BLT1G, BC857BLT1G, BC847BLT1G, BC847BLT1G"></ROW>
    <ROW Designator="Q5, Q6, Q7, Q8" Footprint="TO227" Quantity="4" Value="IRFP260" pn="4180G; RM3X10MM 2701; IRFP260MPBF; 28N65M2; C3M0280090D"></ROW>
    <ROW Designator="R32, R33, R34, R35" Footprint="1210_W" Quantity="4" Value="100k" pn="RMCF1210JT100K"></ROW>
    <ROW Designator="R36, R37" Footprint="0805_W" Quantity="2" Value="10k" pn="RMCF0805JT10K0"></ROW>
    <ROW Designator="R38.1, R38.2, R42.1, R42.2" Footprint="1210_W" Quantity="4" Value="22R" pn="RMCF1210JT22R0"></ROW>
    <ROW Designator="T1.1, T1.2" Footprint="Trafo" Quantity="2" Value="Wurth 1:2" pn="760390015"></ROW>
    <ROW Designator="U1.1, U1.2" Footprint="SOIC-14N" Quantity="2" Value="LM339" pn="LM339DT"></ROW>
    <ROW Designator="U2.1, U2.2" Footprint="SOT-23-TT3_M" Quantity="2" Value="TL431AMFDT,215" pn="TL431AMFDT&#92;,215"></ROW>
    <ROW Designator="U3.1, U3.2" Footprint="SOT-23_L" Quantity="2" Value="MCP9700T" pn="MCP9700T-E/TT"></ROW>
    <ROW Designator="U4.1, U4.2" Footprint="SOT353" Quantity="2" Value="74AHCT1G08" pn="74AHCT1G08SE-7"></ROW>
    <ROW Designator="U7.1, U7.2" Footprint="SOIC16_M" Quantity="2" Value="TL494" pn="TL494IDR"></ROW>
    <ROW Designator="U8.1, U8.2" Footprint="LM78XX" Quantity="2" Value="LM7805" pn="UA78M05CDCY"></ROW>
  </ROWS>
</GRID>
